### ISSUE TITLE
autodeploy to heroku

### ISSUE THREAD

**Issue by keathley** [chadev/butler#2]
It would be really nice to not have to manually deploy each time we merge something into master.

**Comment by colinrymer** [comment]
@keathley Who has access to the Heroku account? If they can add me as a collaborator (`colin.rymer@gmail.com`), I can set this up in a jiffy.

**Comment by colinrymer** [comment]
Also, PR Review bots!!!

**Comment by keathley** [comment]
@colinrymer added
