### ISSUE TITLE
Include setup instructions for Elixir in Readme

### ISSUE THREAD

**Issue by juzten** [chadev/butler#4]
I'd suggest either adding instructions or linking to instructions for setting up Elixir. The following is what I had to do to get butler running...

```
brew update
brew install elixir
export PATH="$PATH:/usr/local/Cellar/elixir/1.1.1/bin"
mix deps.get
```

**Comment by keathley** [comment]
Thats a great point. I've updated the README.

**Comment by juzten** [comment]
:thumbsup:

**Comment by colinrymer** [comment]
@juzten, FWIW, you shouldn't need to set the path for a brew installed elixir. It's automatically symlinked to `/usr/local/bin` which should already be in your path (or the only thing you add if necessary).
